import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

conn=mysql.connector.connect(
    host="localhost",
    user="root",
    password="theycreate_basit_password_"  # Update this password with your MySQL password
)

cursor=conn.cursor()

cursor.execute("create database if not exists sales_analysis")
cursor.execute("use sales_analysis")

cursor.execute(
    """create table if not exists sales(
        id int auto_increment primary key,
        date date,
        product varchar(100),
        quantity int,
        price float
        )"""
)

sample_data = [
    ('2025-01-02', 'Laptop', 1, 950),
('2025-01-03', 'Wireless Mouse', 2, 25),
('2025-01-05', 'Mechanical Keyboard', 1, 120),
('2025-01-08', 'Monitor', 2, 300),
('2025-01-12', 'USB-C Cable', 5, 10),
('2025-01-15', 'Headphones', 1, 80),
('2025-01-18', 'External Hard Drive', 1, 150),
('2025-01-22', 'Laptop Stand', 2, 40),
('2025-02-01', 'Laptop', 2, 950),
('2025-02-04', 'Wireless Mouse', 3, 25),
('2025-02-06', 'Monitor', 1, 300),
('2025-02-10', 'Keyboard', 2, 120),
('2025-02-14', 'USB-C Cable', 8, 10),
('2025-02-18', 'Headphones', 2, 80),
('2025-02-20', 'External Hard Drive', 1, 150),
('2025-03-02', 'Laptop', 1, 950),
('2025-03-05', 'Wireless Mouse', 4, 25),
('2025-03-07', 'Mechanical Keyboard', 1, 120),
('2025-03-12', 'Monitor', 3, 300),
('2025-03-15', 'USB-C Cable', 10, 10),
('2025-03-18', 'Headphones', 2, 80),
('2025-03-20', 'Laptop Stand', 3, 40),
('2025-04-01', 'Laptop', 1, 950),
('2025-04-03', 'Wireless Mouse', 2, 25),
('2025-04-05', 'Monitor', 2, 300),
('2025-04-08', 'Keyboard', 1, 120),
('2025-04-12', 'External Hard Drive', 2, 150),
('2025-04-15', 'USB-C Cable', 12, 10),
('2025-04-18', 'Headphones', 1, 80),
('2025-04-22', 'Laptop Stand', 2, 40),
('2025-05-02', 'Laptop', 2, 950),
('2025-05-05', 'Wireless Mouse', 5, 25),
('2025-05-07', 'Mechanical Keyboard', 2, 120),
('2025-05-10', 'Monitor', 1, 300),
('2025-05-14', 'USB-C Cable', 15, 10),
('2025-05-18', 'External Hard Drive', 2, 150),
('2025-05-20', 'Headphones', 3, 80),
('2025-06-01', 'Laptop', 1, 950),
('2025-06-04', 'Wireless Mouse', 3, 25),
('2025-06-07', 'Monitor', 2, 300),
('2025-06-10', 'Keyboard', 2, 120),
('2025-06-14', 'USB-C Cable', 20, 10),
('2025-06-18', 'Laptop Stand', 4, 40),
('2025-06-22', 'Headphones', 2, 80),
('2025-06-25', 'External Hard Drive', 1, 150)
]

cursor.execute("delete from sales")

insert_query="""
    insert into sales (date,product,quantity,price)
    values(%s,%s,%s,%s)
"""

cursor.executemany(insert_query,sample_data)
conn.commit()

query="select * from sales"
df=pd.read_sql(query,conn)

df=df.drop_duplicates()
df["date"]=pd.to_datetime(df["date"])


df["revenue"]=df["quantity"]*df["price"]

total_revenue=df["revenue"].sum()

print("Total Revenue: ", total_revenue)

df["month"]=df["date"].dt.to_period("M")
monthly_sales=df.groupby("month")["revenue"].sum()

monthly_growth=monthly_sales.pct_change()*100

print("\nMonthly Sales: \n",monthly_sales)
print("\nMonthly Growth (%): \n",monthly_growth)


best_product=df.groupby("product")["revenue"].sum().sort_values(ascending=False)

print("\nRevenue by Product: \n",best_product)
print("\nBest Selling Product: ",best_product.index[0])

mean_revenue=np.mean(df["revenue"])
median_revenue=np.median(df["revenue"])
std_revenue=np.std(df["revenue"])

print("\nMean Revenue:", mean_revenue)
print("Median Revenue:", median_revenue)
print("Standard Deviation:", std_revenue)


x = np.arange(len(monthly_sales))
y = monthly_sales.values

slope, intercept = np.polyfit(x, y, 1)

print("\nSales Trend Slope:", slope)

if slope > 0:
    print("Trend: Increasing")
else:
    print("Trend: Decreasing ")


plt.figure()
plt.plot(monthly_sales.index.astype(str), monthly_sales.values)
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


product_sales = df.groupby('product')['revenue'].sum()

plt.figure()

product_sales.plot(kind='bar')

plt.title("Revenue Generated by Each Product")
plt.xlabel("Product")
plt.ylabel("Total Revenue")

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()



cursor.close()
conn.close()